### ISSUE TITLE
require("crypto") results in a large bundle

### ISSUE THREAD

**Issue by kevinbarabash** [sqren/frametalk#3]
It could be replaced with https://github.com/adamhalasz/uniqid which has no dependencies when used with webpack.

**Comment by sqren** [comment]
Good point. Maybe this can just be replaced something as simple as an incrementing counter:

```js
let uniqueId = 0;
function getUniqueId() {
	return uniqueId++;
}
```

**Comment by kevinbarabash** [comment]
That works for me.
